import{solveBaseflow}from"./solver.js";
const presets={
"Custom":{},
"Validation | Oz-Kara Fig. 3 | M=2.8 | adiabatic":{caseName:"oz_kara_M2p8_adiabatic",mach:2.8,te:121.11,unitRe:1e6,wall:"Adiabatic"},
"Validation | Oz-Kara Fig. 3 | M=4.5 | adiabatic":{caseName:"oz_kara_M4p5_adiabatic",mach:4.5,te:61.584,unitRe:1e6,wall:"Adiabatic"}};
const $=id=>document.getElementById(id),defaults={caseName:"custom_baseflow",mach:5,te:100,x:.1,gamma:1.4,pr:.72,sutherland:110.4,unitRe:1e6,wall:"Adiabatic",tw:300,etaMax:12,points:2001};let result;
for(const name of Object.keys(presets))$("preset").add(new Option(name,name));$("preset").value=Object.keys(presets)[2];
function fill(v){const x={...defaults,...v};for(const k of Object.keys(defaults))$(k).value=x[k];wallState()}
function wallState(){$("tw").disabled=$("wall").value==="Adiabatic"}
$("preset").onchange=()=>fill(presets[$("preset").value]);$("wall").onchange=wallState;fill(presets[$("preset").value]);
function config(){const c={};for(const k of["mach","te","x","gamma","pr","sutherland","unitRe","tw","etaMax","points"])c[k]=Number($(k).value);c.points=Math.round(c.points);c.caseName=$("caseName").value.trim()||"baseflow";c.wall=$("wall").value;return c}
function svgChart(data,key,title,xlabel){const W=240,H=400,m={l:55,r:12,t:18,b:48},vals=data.map(d=>d[key]),ys=data.map(d=>d.y_m*1e3),xmin=Math.min(0,...vals),xmax=Math.max(...vals)*1.04,ymax=Math.max(...ys)*1.02,sx=x=>m.l+(x-xmin)/(xmax-xmin)*(W-m.l-m.r),sy=y=>H-m.b-y/ymax*(H-m.t-m.b),path=data.map((d,i)=>`${i?'L':'M'}${sx(d[key]).toFixed(2)},${sy(d.y_m*1e3).toFixed(2)}`).join(" ");let grid="";for(let i=0;i<=4;i++){const y=i*ymax/4,py=sy(y);grid+=`<line x1="${m.l}" y1="${py}" x2="${W-m.r}" y2="${py}"/><text x="${m.l-7}" y="${py+4}" text-anchor="end">${y.toFixed(ymax<10?1:0)}</text>`}return`<div class="chart"><h3>${title}</h3><svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg"><g stroke="#e4e9e7" stroke-width="1">${grid}</g><g fill="#718086" font-size="9" font-family="monospace"><text transform="rotate(-90 12 ${H/2})" x="12" y="${H/2}">y [mm]</text><text x="${W/2}" y="${H-12}" text-anchor="middle">${xlabel}</text></g><path d="${path}" fill="none" stroke="#176b72" stroke-width="2.5"/><line x1="${m.l}" y1="${m.t}" x2="${m.l}" y2="${H-m.b}" stroke="#758489"/><line x1="${m.l}" y1="${H-m.b}" x2="${W-m.r}" y2="${H-m.b}" stroke="#758489"/></svg></div>`}
function schematic(delta=null,x=null){const W=760,H=250,left=55,right=720,wall=185,top=42,xe=x??Number($("x").value),dm=delta?delta*1e3:null;let path=`M${left},${wall}`;for(let i=0;i<=60;i++){const q=i/60,py=wall-(dm?132:82)*Math.sqrt(q);path+=` L${left+(right-left)*q},${py}`}const label=dm?`δ₉₉(${xe.toPrecision(4)} m) = ${dm.toFixed(4)} mm`:"δ₉₉(x) ∝ √x · generate for dimensional value";$("schematic").innerHTML=`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="bl" x1="0" y1="1" x2="0" y2="0"><stop stop-color="#68aaa6" stop-opacity=".38"/><stop offset="1" stop-color="#68aaa6" stop-opacity=".05"/></linearGradient><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#176b72"/></marker></defs><text x="24" y="25" font-family="monospace" font-size="11" fill="#66777d">FLAT-PLATE BOUNDARY-LAYER DEVELOPMENT</text><path d="${path} L${right},${wall} Z" fill="url(#bl)"/><path d="${path}" fill="none" stroke="#e9633b" stroke-width="3"/><path d="M${left-18},${wall} L${right+15},${wall}" stroke="#10232b" stroke-width="7"/><path d="M26 69H165 M26 91H192 M26 113H220" stroke="#176b72" stroke-width="2" marker-end="url(#arrow)"/><text x="27" y="56" font-family="monospace" font-size="11" fill="#176b72">Uₑ</text><line x1="${right}" y1="${top}" x2="${right}" y2="${wall}" stroke="#e9633b" stroke-dasharray="4 4"/><text x="${right-8}" y="${top-9}" text-anchor="end" font-family="monospace" font-size="12" fill="#ad4226">${label}</text><text x="${right}" y="${wall+30}" text-anchor="end" font-family="monospace" font-size="11" fill="#66777d">x = ${xe.toPrecision(4)} m</text><text x="24" y="235" font-family="monospace" font-size="9" fill="#849396">Vertical scale exaggerated for visibility; labelled δ₉₉ is dimensional.</text></svg>`}
function growthChart(s,c){const W=760,H=260,m={l:70,r:24,t:20,b:52},xmax=c.x,dmax=s.delta99_m*1e3,sx=x=>m.l+x/xmax*(W-m.l-m.r),sy=d=>H-m.b-d/(dmax*1.08)*(H-m.t-m.b);let path="";for(let i=0;i<=150;i++){const x=xmax*i/150,d=dmax*Math.sqrt(i/150);path+=`${i?'L':'M'}${sx(x).toFixed(2)},${sy(d).toFixed(2)} `}let grid="";for(let i=0;i<=4;i++){const d=dmax*i/4,py=sy(d);grid+=`<line x1="${m.l}" y1="${py}" x2="${W-m.r}" y2="${py}"/><text x="${m.l-8}" y="${py+4}" text-anchor="end">${d.toFixed(2)}</text>`}return`<h3>Boundary-layer growth along the plate</h3><svg class="plot-export" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg"><g stroke="#e4e9e7">${grid}</g><path d="${path}" fill="none" stroke="#e9633b" stroke-width="3"/><circle cx="${sx(xmax)}" cy="${sy(dmax)}" r="5" fill="#10232b"/><g fill="#718086" font-size="10" font-family="monospace"><text x="${W/2}" y="${H-12}" text-anchor="middle">x [m]</text><text transform="rotate(-90 15 ${H/2})" x="15" y="${H/2}">δ₉₉ [mm]</text><text x="${sx(xmax)-8}" y="${sy(dmax)-10}" text-anchor="end">${dmax.toFixed(4)} mm at x=${xmax.toPrecision(4)} m</text></g><line x1="${m.l}" y1="${m.t}" x2="${m.l}" y2="${H-m.b}" stroke="#758489"/><line x1="${m.l}" y1="${H-m.b}" x2="${W-m.r}" y2="${H-m.b}" stroke="#758489"/></svg>`}
function render(){const d=result.data,s=result.meta.solution_summary,c=result.meta.input;$("output").hidden=false;schematic(s.delta99_m,c.x);$("mRe").textContent=result.meta.derived_edge_conditions.unit_Re_1_m.toExponential(3);$("mDelta").textContent=(s.delta99_m*1e3).toFixed(4);$("mTw").textContent=s.Tw_K.toFixed(2);$("mResidual").textContent=s.boundary_residual_max.toExponential(1);$("growthChart").innerHTML=growthChart(s,c);$("charts").innerHTML=svgChart(d,"u_over_ue","Velocity","u / Ue")+svgChart(d,"T_over_Te","Temperature","T / Te")+svgChart(d,"rho_over_rhoe","Density","ρ / ρe");document.querySelectorAll(".chart svg").forEach(svg=>svg.classList.add("plot-export"))}
$("generate").onclick=()=>{const b=$("generate"),msg=$("message");b.disabled=true;msg.className="message";msg.textContent="Solving the nonlinear boundary-value problem…";setTimeout(()=>{try{result=solveBaseflow(config());render();msg.textContent="Profile generated. Download files below."}catch(e){msg.className="message error";msg.textContent=e.message}finally{b.disabled=false}},30)};
const cols=["eta","y_bar","y_m","u_over_ue","T_over_Te","rho_over_rhoe","mu_over_mue","C","u_m_s","T_K","rho_kg_m3","mu_Pa_s","p_Pa","du_dy_1_s","dT_dy_K_m","drho_dy_kg_m4","f","fpp","dT_deta"];
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function stem(){return result.meta.input.caseName.replace(/[^A-Za-z0-9_.-]+/g,"_")}
$("csv").onclick=()=>download(new Blob([[cols.join(","),...result.data.map(d=>cols.map(k=>d[k]).join(","))].join("\n")],{type:"text/csv"}),stem()+"_baseflow.csv");
$("json").onclick=()=>download(new Blob([JSON.stringify(result.meta,null,2)],{type:"application/json"}),stem()+"_metadata.json");
$("png").onclick=()=>{const svgs=[...document.querySelectorAll(".plot-export")],canvas=document.createElement("canvas");canvas.width=1200;canvas.height=1030;const c=canvas.getContext("2d");c.fillStyle="white";c.fillRect(0,0,canvas.width,canvas.height);let done=0;svgs.forEach((svg,i)=>{const img=new Image();img.onload=()=>{if(i===0)c.drawImage(img,0,0,1200,410);else c.drawImage(img,(i-1)*400,410,400,620);if(++done===svgs.length)canvas.toBlob(b=>download(b,stem()+"_profiles.png"))};img.src="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(new XMLSerializer().serializeToString(svg))})};
schematic();
