const R_AIR=287.05, MU_REF=1.716e-5, T_REF=273.15;

function rhs(y,c){const [f,fp,fpp,g,gp]=y;if(g<=0||!Number.isFinite(g))throw Error("Temperature ratio became non-positive");const th=c.sutherland/c.te,rg=Math.sqrt(g);let fppp=-fpp*(gp/(2*g)-gp/(g+th))-f*fpp*(g+th)/(rg*(1+th));let gpp=-gp*gp*(.5/g-1/(g+th))-c.pr*f*gp*(g+th)/(rg*(1+th))-(c.gamma-1)*c.pr*c.mach*c.mach*fpp*fpp;return[fp,fpp,fppp,gp,gpp]}
function add(a,b,s=1){return a.map((v,i)=>v+s*b[i])}
function integrate(c,shoot,save=false){const n=Math.max(1800,Math.ceil(c.etaMax*220)),h=c.etaMax/n;let y=c.wall==="Adiabatic"?[0,0,shoot[0],shoot[1],0]:[0,0,shoot[0],c.tw/c.te,shoot[1]];const rows=save?[[0,...y]]:null;for(let i=0;i<n;i++){const k1=rhs(y,c),k2=rhs(add(y,k1,h/2),c),k3=rhs(add(y,k2,h/2),c),k4=rhs(add(y,k3,h),c);y=y.map((v,j)=>v+h*(k1[j]+2*k2[j]+2*k3[j]+k4[j])/6);if(save)rows.push([(i+1)*h,...y])}return save?rows:y}
function residual(c,s){const y=integrate(c,s);return[y[1]-1,y[3]-1]}
function norm(v){return Math.max(...v.map(Math.abs))}
function shoot(c){const recovery=Math.sqrt(c.pr)*.5*(c.gamma-1)*c.mach*c.mach;let s=c.wall==="Adiabatic"?[.35,1+recovery]:[.5,.15*recovery];let r=residual(c,s);for(let it=0;it<24;it++){if(norm(r)<2e-9)return{s,residual:norm(r),iterations:it};const j=[[],[]];for(let k=0;k<2;k++){const e=1e-5*Math.max(1,Math.abs(s[k])),sp=[...s];sp[k]+=e;const rp=residual(c,sp);j[0][k]=(rp[0]-r[0])/e;j[1][k]=(rp[1]-r[1])/e}const det=j[0][0]*j[1][1]-j[0][1]*j[1][0];if(!Number.isFinite(det)||Math.abs(det)<1e-13)throw Error("Shooting Jacobian is singular");const d=[(-r[0]*j[1][1]+j[0][1]*r[1])/det,(j[1][0]*r[0]-j[0][0]*r[1])/det];let accepted=false;for(const a of[1,.5,.25,.125,.0625,.03125]){const sn=[s[0]+a*d[0],s[1]+a*d[1]];try{const rn=residual(c,sn);if(norm(rn)<norm(r)){s=sn;r=rn;accepted=true;break}}catch{}}if(!accepted)throw Error("Nonlinear shooting did not converge")};throw Error("Nonlinear shooting exceeded 24 iterations")}
function interp(rows,count){const out=[];for(let k=0;k<count;k++){const q=k*(rows.length-1)/(count-1),i=Math.min(rows.length-2,Math.floor(q)),a=q-i;out.push(rows[i].map((v,j)=>v*(1-a)+rows[i+1][j]*a))}return out}
export function solveBaseflow(c){for(const key of["mach","te","x","gamma","pr","sutherland","unitRe","etaMax","points"])if(!(c[key]>0))throw Error(`${key} must be positive`);if(c.gamma<=1)throw Error("gamma must exceed one");if(c.wall==="Isothermal"&&!(c.tw>0))throw Error("Wall temperature must be positive");const shot=shoot(c),raw=integrate(c,shot.s,true),rows=interp(raw,c.points);let ybar=0;const ue=c.mach*Math.sqrt(c.gamma*R_AIR*c.te),mue=MU_REF*(c.te/T_REF)**1.5*(T_REF+c.sutherland)/(c.te+c.sutherland),rhoe=c.unitRe*mue/ue,pe=rhoe*R_AIR*c.te,nue=mue/rhoe,scale=Math.sqrt(2*nue*c.x/ue);const data=[];for(let i=0;i<rows.length;i++){const [eta,f,fp,fpp,g,gp]=rows[i];if(i){const prev=rows[i-1];ybar+=(eta-prev[0])*(g+prev[4])/2}const rr=1/g,mur=g**1.5*(1+c.sutherland/c.te)/(g+c.sutherland/c.te),ym=ybar*scale;data.push({eta,y_bar:ybar,y_m:ym,u_over_ue:fp,T_over_Te:g,rho_over_rhoe:rr,mu_over_mue:mur,C:rr*mur,u_m_s:fp*ue,T_K:g*c.te,rho_kg_m3:rr*rhoe,mu_Pa_s:mur*mue,p_Pa:pe,du_dy_1_s:ue*fpp/(scale*g),dT_dy_K_m:c.te*gp/(scale*g),drho_dy_kg_m4:-rhoe*gp/(scale*g**3),f,fpp,dT_deta:gp})}const d99=data.find(d=>d.u_over_ue>=.99)?.y_m??NaN;return{data,meta:{input:c,derived_edge_conditions:{Ue_m_s:ue,pe_Pa:pe,rho_e_kg_m3:rhoe,mu_e_Pa_s:mue,nu_e_m2_s:nue,unit_Re_1_m:c.unitRe,Re_x:c.unitRe*c.x},solution_summary:{Tw_K:data[0].T_K,Tw_over_Te:data[0].T_over_Te,delta99_m:d99,boundary_residual_max:shot.residual,shooting_iterations:shot.iterations},formulation:"Oz-Kara compressible Blasius similarity equations; perfect gas; Sutherland viscosity; zero pressure gradient.",validation:"Adiabatic formulation benchmarked against Oz & Kara Figure 3. Browser solver cross-checked against the SciPy BVP implementation."}}}
